apiVersion: v2
name: activemq-artemis
version: 0.0.4
description: a multi-protocol, embeddable, very high performance, clustered, asynchronous messaging system.
keywords:
- activemq
- artemis
- messaging
- mom
- amqp
- jms
maintainers:
  - name: OSGP
    email: gxf@lists.lfenergy.org
    url: https://www.lfenergy.org/projects/gxf/
home: https://activemq.apache.org/artemis/
icon: https://activemq.apache.org/artemis/images/activemq-logo.png
sources:
- https://github.com/kubernetes/charts
- https://github.com/apache/activemq-artemis
engine: gotpl
