{{ if .Values.efsStorage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.efsStorage.name . | default .Release.Name }}-pvc
spec:
  storageClassName: {{ .Values.efsStorage.class | default "efs" }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{ end }}
